### ISSUE TITLE
Code implementation of Multisampling described in the paper

### ISSUE THREAD

**Issue by Bin-ze** [jake-austin/zipnerf-nerfstudio#3]
In the func get_density(), n_multisamples is set to 1，Is this just an easy implementation for running through the code quickly?

I want to try to implement the spatial Anti-Aliasing described in the paper.

As mentioned in your README, the most critical part is multisampling and downweighting. I am looking at this code carefully, but it is a bit difficult, if you can tell me which parts are currently implemented, which parts are missing, and where may cause problems, it should be conducive to the development of subsequent work.

My suggestion is to list the core difficulties of zip-nerf reproduction, so that you can concentrate on completing the unfinished part.

**Comment by jake-austin** [comment]
Yeah this is just for debugging

@terrancewang has also been observing some issues with the implementation we have for the proposal supervision loss too, so nothing is safe haha. I can try and go back and enumerate the issues more explicitly, but we're not certain of anything at this point
